list: $/svetlana/driverapp/models/cartype/columns.yaml
modelClass: Svetlana\DriverApp\Models\CarType
title: CarTypes
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'svetlana/driverapp/cartypes/update/:id'
