list: $/svetlana/driverapp/models/order/columns.yaml
modelClass: Svetlana\DriverApp\Models\Order
title: Orders
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'svetlana/driverapp/orders/update/:id'
